feat: add landing page and summernote
pythonalicante/Meetup-Selector pull request #35
Opened 2020-10-23 16:59 UTC by fermartv

2020-10-23 18:01 UTC, aalmiramolla requested changes
Please, say if you can review and change the problems or I make the fix!
Thanks!

2020-10-23 18:01 UTC, aalmiramolla commented on meetupselector/settings.py
> +# MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
This lines are already declared on line 136-141

2020-10-23 18:05 UTC, aalmiramolla commented on meetupselector/landingpage/models.py
> +class LandingPageContent(models.Model):
We are in LandingPage App, I think "Content" is enough as model name

2020-10-23 18:13 UTC, aalmiramolla commented on meetupselector/landingpage/models.py
> +class LandingPageContent(models.Model):
We should add `__str__` method for represent better the objects in admin

2020-10-23 18:13 UTC, aalmiramolla commented on meetupselector/landingpage/models.py
> +class LandingPageContent(models.Model):
I think we can add a new field, `title`, so we can represent the object by the title.

2020-10-24 17:34 UTC, fermartv commented on meetupselector/landingpage/views.py
> +            'content': LandingPageContent.objects.all()[0]
Why would you have more than one content object? In that case which one should be rendered?

2020-10-25 14:52 UTC, serfer2 requested changes
You did a good job. I left few comments with some improvement proposals.

2020-10-25 14:52 UTC, serfer2 commented on meetupselector/landingpage/models.py
> +        return self.title
I think we should add a `date_added` field with `auto_now = True`.
And, what's the default ordering for that model? I guess latests contents should be rendered first. So, I would suggest to add a ordering option with `'-date_added'` as default ordering.

2020-10-25 14:52 UTC, serfer2 commented on meetupselector/landingpage/admin.py
> +admin.site.register(Content, ContentAdmin)
I left a comment in `models.py`, suggesting to add a `date_added` field.
It would be nice to add that field to `list_display` in admin and set it as `read_only`. I suggest you to take a look to `TopicProposalAdmin` as an example.

2020-10-25 14:52 UTC, serfer2 commented on meetupselector/landingpage/tests/test_views.py
> +        response = self.client.get(self.url)
We should add almost one more test. That test should have some `Content` objects created, in order to verify the rendering of objects content in correct order.

2020-10-25 18:42 UTC, aalmiramolla commented on meetupselector/landingpage/views.py
> +            'content': LandingPageContent.objects.all()[0]
We need as many Content as admin want's and all should be rendered.

2020-10-25 18:47 UTC, aalmiramolla requested changes
Thanks for improving the code, fix @serfer2 comments and PR is done!!

2020-10-25 18:47 UTC, aalmiramolla commented on meetupselector/landingpage/views.py
> +            content.save()
Good work! I like this approach!

2020-10-27 19:27 UTC, merged